### PR TITLE
added commenting functionality

### PR DESCRIPTION
**Pull request by FionaBai**
Now can leave comments, unable to set up username, and comments will disappear once you refresh the page.

### CODE REVIEW

**Review by JC011118 — DISMISSED** [review]
Good change for the comment-section.

**Comment by qianhuazhou** [comment]
Nice improvement.

**Review by qianhuazhou — DISMISSED** [review]

**Review by xsshao — DISMISSED** [review]
Looking good

**Review by JC011118 — DISMISSED** [review]
Nice

**Review by qianhuazhou — DISMISSED** [review]

**Review by JC011118 — APPROVED** [review]
Nice

**Review by qianhuazhou — APPROVED** [review]

**Review by xsshao — APPROVED** [review]
well done!

**Pull request merged**
