### PR TITLE
Created basic html page

### PR DESCRIPTION
**Pull request by xsshao**
- Created a basic static html/css page for our app
- There are two html page, a home page and a upload image page(building.html)
- For the home page, there are three section: hyperlink to upload image page, project description, team info
- For the building.html, there are also three sections: upload section, building information section, comments section
- For the CSS file, we only added the official uiuc orange and blue color and other simple properties

### CODE REVIEW

**Review by JC011118 — APPROVED** [review]
Like what you have so far. The code is well-structured with good readability. It thinks the website contains most of the information we want so far. I think one thing to work on in the future is the upload history section if we still decide to have it.

**Comment by QianhuaZhou** [comment]
The code is well-organized and easy to follow, and the website seems to include most of the information we need. To make the interface more user-friendly, might consider adjusting the text size and opting for a lighter background color.

**Review by qianhuazhou — APPROVED** [review]
The code is well-organized and easy to follow, and the website seems to include most of the information we need. To make the interface more user-friendly, might consider adjusting the text size and opting for a lighter background color.

**Review by FionaBai — APPROVED** [review]
Looks good!

**Pull request merged**
